name: barber_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  animate_do: ^4.2.0
  cached_network_image: ^3.4.1
  firebase_auth: ^5.5.4
  firebase_cloud_firestore: ^5.4.4
  firebase_core: ^3.13.1
  firebase_storage: ^12.4.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  persistent_bottom_nav_bar: ^6.2.1
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
