enum RouterNames {
  splashScreen,
  welcomePage,
  loginPage,
  registerPage,
  roleSelectionPage,
  homePage,
  adminPage,

  forgotPasswordPage,
  feedPage,
  feedsPage,
  searchPage,
  notificationsPage,
  settingsPage,
  userProfilePage,
  postDetailPage,
  editProfilePage,
  authPage,
}
