// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDthH2coFws0ypinvWmQMmndDrZxunztXg',
    appId: '1:247639188244:web:1e3b06304f8d496dbf1801',
    messagingSenderId: '247639188244',
    projectId: 'barber-app-b78ef',
    authDomain: 'barber-app-b78ef.firebaseapp.com',
    storageBucket: 'barber-app-b78ef.firebasestorage.app',
    measurementId: 'G-90GSSC0LTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRlDzBKlnwDj3etfRclxVvE7UDnu9gwrc',
    appId: '1:247639188244:android:9065bf77fa0c54bfbf1801',
    messagingSenderId: '247639188244',
    projectId: 'barber-app-b78ef',
    storageBucket: 'barber-app-b78ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2fNC9kmoCXs_pOGu5XmaGXiEm5wJYMhM',
    appId: '1:247639188244:ios:8bef45f1acc8f397bf1801',
    messagingSenderId: '247639188244',
    projectId: 'barber-app-b78ef',
    storageBucket: 'barber-app-b78ef.firebasestorage.app',
    iosBundleId: 'com.example.barberApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2fNC9kmoCXs_pOGu5XmaGXiEm5wJYMhM',
    appId: '1:247639188244:ios:8bef45f1acc8f397bf1801',
    messagingSenderId: '247639188244',
    projectId: 'barber-app-b78ef',
    storageBucket: 'barber-app-b78ef.firebasestorage.app',
    iosBundleId: 'com.example.barberApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDthH2coFws0ypinvWmQMmndDrZxunztXg',
    appId: '1:247639188244:web:57c5df70b420ba0cbf1801',
    messagingSenderId: '247639188244',
    projectId: 'barber-app-b78ef',
    authDomain: 'barber-app-b78ef.firebaseapp.com',
    storageBucket: 'barber-app-b78ef.firebasestorage.app',
    measurementId: 'G-VK31J8YBP1',
  );
}
